USE master;

DROP DATABASE IF EXISTS LocalProduce;

CREATE DATABASE LocalProduce;



CREATE table FarmersMarket
(
	FMID			int				not null,		
	MarketName		varchar(150)	not null,
	Website			varchar(150)	null,
	Facebook		varchar(150)	null,
	Twitter			varchar(150)	null,
	Youtube			varchar(150)	null,
	OtherMedia		varchar(150)	null,
	street			varchar(150)	not null,
	city			varchar(150)	not null,
	County			varchar(150)	not null,
	State			varchar(150)	not null,
	zip				varchar(150)	not null,
	Season1Date		varchar(60)		null,
	Season1Time		varchar(60)		null,
	Season2Date		varchar(60)		null,
	Season2Time		varchar(60)		null,
	Season3Date		varchar(60)		null,
	Season3Time		varchar(60)		null,
	Season4Date		varchar(60)		null,
	Season4Time		varchar(60)		null,
	x				varchar(60)		null,
	y				varchar(60)		null,
	Location		varchar(60)		null,
	Credit			varchar(60)		null,
	WIC				varchar(1)		null,
	WICcash			varchar(1)		null,
	SFMNP			varchar(1)		null,
	SNAP			varchar(1)		null,
	Organic			varchar(1)		null,
	Bakedgoods		varchar(1)		null,
	Cheese			varchar(1)		null,
	Crafts			varchar(1)		null,
	Flowers			varchar(1)		null,
	Eggs			varchar(1)		null,
	Seafood			varchar(1)		null,
	Herbs			varchar(1)		null,
	Vegetables		varchar(1)		null,
	Honey			varchar(1)		null,
	Jams			varchar(1)		null,
	Maple			varchar(1)		null,
	Meat			varchar(1)		null,
	Nursery			varchar(1)		null,
	Nuts			varchar(1)		null,
	Plants			varchar(1)		null,
	Poultry			varchar(1)		null,
	Prepared		varchar(1)		null,	
	Soap			varchar(1)		null,
	Trees			varchar(1)		null,
	Wine			varchar(1)		null,
	Coffee			varchar(1)		null,
	Beans			varchar(1)		null,
	Fruits			varchar(1)		null,
	Grains			varchar(1)		null,
	Juices			varchar(1)		null,
	Mushrooms		varchar(1)		null,	
	PetFood			varchar(1)		null,
	Tofu			varchar(1)		null,
	WildHarvested	varchar(1)		null,
	updateTime		varchar(150)	null,
	
	constraint pk_FarmersMarket	primary key (FMID)

);


CREATE TABLE OnFarmMarketDirectory
(

	OF_ID				int				not null,
	createTime			varchar(150)	null,
	updateTime			varchar(150)	null,
	finishTime			varchar(150)	null,
	Location_ST			varchar(150)	not null,
	Location_City		varchar(150)	not null,
	Location_State		varchar(150)	not null,
	Location_StateFIPS	varchar(150)	not null,
	Location_Zip		varchar(150)	not null,
	x					varchar(150)	null,
	y					varchar(150)	null,
	marketname			varchar(150)	not null,
	Market_Website		varchar(150)	null,
	Market_Facebook		varchar(150)	null,
	Market_Twitter		varchar(150)	null,
	season1_date		varchar(150)	null,
	season1_time		varchar(150)	null,
	season1_notes		varchar(150)	null,
	season1_products	varchar(500)	null,
	season2_date		varchar(150)	null,
	season2_time		varchar(150)	null,
	season2_notes		varchar(150)	null,
	season2_products	varchar(500)	null,	
	season3_date		varchar(150)	null,
	season3_time		varchar(150)	null,
	season3_notes		varchar(150)	null,
	season3_products	varchar(500)	null,
	season4_date		varchar(150)	null,
	season4_time		varchar(150)	null,
	season4_notes		varchar(150)	null,
	season4_products	varchar(500)	null,	
	Product_1_baked_goods						varchar(1)		null,
	Product_2_bedding_plants					varchar(1)		null,
	Product_3_canned_preserved					varchar(1)		null,
	Product_4_coffee_tea						varchar(1)		null,
	Product_5_crafts_woodworking_items			varchar(1)		null,
	Product_6_cut_flowers						varchar(1)		null,
	Product_7_dairy_products					varchar(1)		null,
	Product_8_dry_beans							varchar(1)		null,
	Product_9_eggs								varchar(1)		null,
	Product_10_fish_seafood						varchar(1)		null,
	Product_11_herbs							varchar(1)		null,
	Product_12_fresh_fruits						varchar(1)		null,
	Product_13_fresh_vegetables					varchar(1)		null,
	Product_14_grains_flour						varchar(1)		null,
	Product_15_honey							varchar(1)		null,
	Product_16_juices_non_alcoholic_ciders		varchar(1)		null,
	Product_17_maple_products					varchar(1)		null,
	Product_18_mushrooms						varchar(1)		null,
	Product_19_nursery_stock					varchar(1)		null,
	Product_20_nuts								varchar(1)		null,
	Product_21_pet_food							varchar(1)		null,
	Product_22_poultry_fowl_meat_products		varchar(1)		null,
	Product_23_prepared_foods					varchar(1)		null,
	Product_24_red_non_poultry_meat_products	varchar(1)		null,
	Product_25_soap_body_care_products			varchar(1)		null,
	Product_26_tofu_non_animal_protein			varchar(1)		null,
	Product_27_wild_harvested_forest_products	varchar(1)		null,
	Product_28_wine_spirits_beer_hard_cider		varchar(1)		null,
	ActivityList		varchar(1000)	null,
	FacilitiesList		varchar(1000)	null,
	Payment_2_cash			varchar(1)		null,
	Payment_3_check			varchar(1)		null,
	Payment_4_debit_credit	varchar(1)		null,
	Payment_1_SNAP			varchar(1)		null,
	

	constraint pk_OnFarmMarketDirectory	primary key (OF_ID)
);


CREATE TABLE CommunitySupportedAgriculture
(
	CSA_ID						int				not null,
	createTime					varchar(150)	null,
	updateTime					varchar(150)	null,
	finishTime					varchar(150)	null,
	Mailing_ST					varchar(150)	not null,
	Mailing_City				varchar(150)	not null,
	Mailing_State				varchar(150)	not null,
	Mailing_StateFIPS			varchar(150)	not null,
	Mailing_Zip					varchar(150)	not null,
	marketname					varchar(150)	not null,
	HQ_ST						varchar(150)	not null,
	HQ_City						varchar(150)	not null,
	HQ_State					varchar(150)	not null,
	HQ_StateFIPS				varchar(150)	not null,
	HQ_Zip						varchar(150)	not null,
	CSA_ManagerName				varchar(150)	null,
	CSA_Email					varchar(150)	null,
	CSA_Phone					varchar(150)	null,
	CSA_Website					varchar(150)	null,
	CSA_Facebook				varchar(150)	null,
	CSA_Twitter					varchar(150)	null,
	CSA_NumYearContinuous		varchar(150)	null,
	CSA_NumYearContinuousDesc	varchar(150)	null,
	Num_Farms_Supply			varchar(100)	null,
	ProductList					varchar(1000)	null,
	FishList					varchar(1000)	null,
	FruitList					varchar(1000)	null,
	VegList						varchar(1000)	null,
	PoultryList					varchar(1000)	null,
	MeatList					varchar(1000)	null,
	Bakedgoods					varchar(1000)	null,
	CSA_organic					varchar(100)		null,
	CSA_organicDesc_farming_practicesList	varchar(1000)		null,
	NumShare_ShareSizeList		varchar(100)		null,
	SharesSize_full_half		varchar(1)		null,
	SharesSize_full				varchar(1)		null,
	SharesAvailablePurchaseDate	varchar(100)		null,
	ItemsInShareBoxList			varchar(1000)		null,
	AccptdPmntList				varchar(1000)		null,
	CSAPaymentTypeList			varchar(1000)		null,
	DeliverPickUpMethodList		varchar(1000)		null,
	NumNbrDelivery				varchar(100)		null,
	NameNbrDelivery				varchar(1000)		null,
	
	constraint pk_CommunitySupportedAgriculture	primary key (CSA_ID)
	
);

CREATE table FoodHubDirectory
(
	FMID							int				not null,
	MarketName						varchar(150)	null,
	createTime						varchar(150)	null,
	updateTime						varchar(150)	null,
	finishTime						varchar(150)	null,
	Mailing_State					varchar(150)	not null,
	Mailing_StateFIPS				varchar(150)	not null,
	Mailing_City					varchar(150)	not null,
	Mailing_ST						varchar(150)	not null,
	Mailing_Zip						varchar(150)	not null,
	Market_ManagerName				varchar(150)	null,
	FH_ContactTitle					varchar(150)	null,
	Market_Email					varchar(150)	null,
	Market_Phone					varchar(150)	null,
	Market_Website					varchar(150)	null,
	Market_Facebook					varchar(150)	null,
	Market_Twitter					varchar(150)	null,
	Location_State					varchar(150)	not null,
	Location_StateFIPS				varchar(150)	not null,
	Location_County					varchar(150)	not null,
	Location_CountyFIPS				varchar(150)	not null,
	Location_ST						varchar(150)	not null,
	Location_City					varchar(150)	not null,
	Location_Zip					varchar(150)	not null,
	Location_Desc					varchar(150)	null,
	EstablishYear					varchar(150)	null,
	Legal_Status					varchar(150)	null,
	Legal_StatusDesc				varchar(150)	null,
	OperationMonthList				varchar(1000)	null,
	Organic							varchar(1)	null,
	OrganicDesc						varchar(150)	null,
	ProductList						varchar(1000)	null,
	ProductListExclusivelylocal		varchar(1000)	null,
	ProductListOnlyLocalWhenAvailable		varchar(1000)	null,
	ProductListLocalNonLocal		varchar(1000)	null,
	ProductListNonlocal				varchar(1000)	null,
	PracticeList					varchar(1000)	null,
	F2BList							varchar(1000)	null,
	ProcurementList					varchar(1000)	null,
	OpserviceList					varchar(1000)	null,
	PSServiceList					varchar(1000)	null,
	CSServiceList					varchar(1000)	null,


	constraint pk_FoodHubDirectory	primary key (FMID)

);
